language: python
python:
          - "2.7"
install:
          - pip install flake8
          - pip install python-coveralls
          - pip install -r voting_script/requirements.txt
          - pip install -r retweeting_script/requirements.txt
script:
          - flake8 --filename= *.py voting_script/ retweeting_script/ || (echo "Please run a linter and fix errors "; false)
after_success:
          - coveralls
