[![Build Status](https://travis-ci.org/surajnarwade/pycon-india-scripts.svg?branch=master)](https://travis-ci.org/https://travis-ci.org/surajnarwade/pycon-india-scripts)

language: python
python:
          - "2.7"
install:
          - pip install flake8
          - pip install coveralls
script:
          - flake8 --filename=*.py voting_script/ retweeting_script/ || (echo "Please run a linter and fix errors "; false)
after_success:
          - coveralls
